### ISSUE TITLE
Not working with Gedit 3.36

### ISSUE THREAD

**Issue by fugo** [jpfleury/gedit-markdown#18]
After update Plugin stops working. New install also not helps.
I have  ``/usr/share/gir-1.0/WebKit2-4.0.gir`` and python-markdown (Python 3.8.2)
Error after trying to activate gedit-markdown:

<pre>** (gedit:15023): <font color="#657B83"><b>WARNING</b></font> **: <font color="#268BD2">19:35:34.301</font>: Error importing plugin &apos;markdown-preview&apos;:
Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked
  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 783, in exec_module
  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
  File &quot;/home/ths/.local/share/gedit/plugins/markdown-preview/__init__.py&quot;, line 21, in &lt;module&gt;
    from gi.repository import Gdk, Gtk, Gedit, GObject, WebKit
  File &quot;/usr/lib/python3.8/site-packages/gi/importer.py&quot;, line 132, in load_module
    raise ImportError(&apos;cannot import name %s, &apos;
ImportError: cannot import name WebKit, introspection typelib not found

(gedit:15023): libpeas-<font color="#657B83"><b>WARNING</b></font> **: <font color="#268BD2">19:35:34.302</font>: Error loading plugin &apos;markdown-preview&apos;</pre>

**Comment by darkdragon-001** [comment]
This issue is fixed in my fork: https://github.com/darkdragon-001/gedit-markdown/

Please test the latest release. Pull requests are always welcome!

**Comment by jpfleury** [comment]
Fixed in latest release.
