### PR TITLE
Make it works with Gedit 3.16.3

### PR DESCRIPTION
**Pull request by R1kk3r**
Make it works with Gedit of the last Debian testing update. For me, it is Gedit 3.16.3 but it can be compatible with other versions as well (not tested).

Quite similar to pull requests #9 but support internationalization and have a stateful menu entry.

### CODE REVIEW

**Comment by marc1uk** [comment]
On gedit 3.14:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marc/.local/share/gedit/plugins/markdown-preview/__init__.py", line 25, in <module>
    from gi.repository import Gio, Gdk, Gtk, Gedit, GObject, WebKit, GLib
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name WebKit, introspection typelib not found

(gedit:6669): libpeas-WARNING **: Error loading plugin 'markdown-preview'

**Comment by sixtyfive** [comment]
So this PR also suffers from the problem of python-webkit being unmaintained. Perhaps close it, then?

**Comment by darkdragon-001** [comment]
I just want to let you know, that I created a fork: https://github.com/darkdragon-001/gedit-markdown/

Please test the latest release. Pull requests are always welcome!
